name: Generate changelog
on:
  # release:
  #   types: [created, edited, published]
  pull_request:
    types: [closed]
  workflow_run:
    workflows: ["Create release"]  # release.ymlì˜ nameê³¼ ì¼ì¹˜í•´ì•¼ í•¨
    types:
      - completed
  workflow_dispatch:  
  
permissions: 
  contents: write
  pull-requests: write

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Get first tag
      id: get_first_tag
      run: |
        # ì‹œë§¨í‹± ë²„ì „ íƒœê·¸ ì¤‘ ê°€ì¥ ìµœì‹  ë²„ì „ ì°¾ê¸° (v1 ì œì™¸)
        latest_tag="$(git tag -l 'v[0-9]*.[0-9]*.[0-9]*' | sort -V | tail -n1)"
        echo "LATEST_TAG=${latest_tag}" >> "$GITHUB_ENV"
        # ì²« ë²ˆì§¸ íƒœê·¸ëŠ” v1.0.0ìœ¼ë¡œ ê³ ì •
        echo "FIRST_TAG=v0.1.0" >> "$GITHUB_ENV"


    - name: Generate changelog
      uses: github-changelog-generator/github-changelog-generator-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        output: CHANGELOG.md
        sinceTag: ${{ env.FIRST_TAG }}
        futureRelease: ${{ env.LATEST_TAG }}
        stripGeneratorNotice: false
        unreleased: true
        unreleasedOnly: false
        pullRequests: true
        prWoLabels: true
        issues: true
        issuesWoLabels: true
        filterByMilestone: false
        compareLink: true
        excludeTagsRegex: "^v[0-9]$"
        breakingLabel: '### âš ï¸ Breaking Changes'
        enhancementLabel: '### ğŸš€ Enhancements'
        bugsLabel: '### ğŸ› Bug Fixes'
        securityLabel: '### ğŸ”’ Security Fixes'
        issuesLabel: '### âš¡ Issues'
        prLabel: '### ğŸ” Pull Requests'
        addSections: '{"documentation":{"prefix":"### ğŸ“ Documentation","labels":["documentation"]}}'

    - name: Git Commit and Push
      uses: somaz94/go-git-commit-action@v1
      with:
        branch: main
        commit_message: "Update changelog"
        user_email: "actions@github.com"
        user_name: "GitHub Actions"
        file_pattern: "CHANGELOG.md"

